name:                readme
version:             0.0.1.0
github:              "gillchristian/readme"
license:             MIT
author:              "gillchristian"
maintainer:          "gillchristian@gmail.com"
copyright:           "2019 Christian Gill"
description:         Please see the README on GitHub at <https://github.com/gillchristian/readme#readme>

extra-source-files:
- readme.md

dependencies:
- base >= 4.7 && < 5
- directory
- aeson
- bytestring
- text
- http-types
- http-client
- servant
- servant-server
- servant-lucid
- lucid
- warp
- transformers
- mtl
- filepath
- cheapskate
- cheapskate-lucid

library:
  source-dirs: src

executables:
  readme:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - readme

tests:
  serve-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - readme
